### ISSUE TITLE
Expand docstrings?

### ISSUE THREAD

**Issue by hoechenberger** [conda-forge/mne-feedstock#80] opened 2022-02-23 08:07 UTC
This one mostly goes out to @larsoner 

cc @agramfort @sappelhoff @mmagnuski

Since 

- VS Code's Pylance [still doesn't support the expansion of our doccer-style docstrings](https://github.com/microsoft/pylance-release/issues/346),
- and we're unlikely to see this feature anytime soon,
- and we once discussed that we don't want to do this expansion for sdist releases either (I think),

I just thought: Why not do it here, during the `conda` build? We are basically free do any modifications we like during the build stage!

It should be a rather straightforward operation, no?

And everybody following our official installation instructions (i.e., ending up with a `conda`-based install) would automatically have fully functional docstrings in VS Code.

WDYT?

**Comment by larsoner** [comment] 2022-02-23 12:09
Sure, seems reasonable. Actually I wonder if we should also do it when building a wheel. Then almost all modes of installation (even from source since that typically builds a wheel locally nowadays I think?) other than editable mode would get this benefit.

**Comment by hoechenberger** [comment] 2022-02-23 12:39
Yes, if you think we could do this when building the sdist, all use cases should be covered, including the `conda` package.

**Comment by larsoner** [comment] 2022-02-23 12:49
I'm actually not talking about the sdist, but the wheel (`.whl`) that we produce and upload to PyPi. I'll have to look up where we discussed this before to see why we shouldn't do it to the sdist.

One drawback this will have is that users traceback line numbers will no longer match those of the actual source code. But given that most of our bug reports come (eventually) with reproducible examples, it's probably worth the tradeoff to have completed docstrings for people.

**Comment by larsoner** [comment] 2022-02-23 12:50
... but regardless of whether we do it to the sdist or not, the function/code to do it during wheel building is exactly the same thing that you'd need for conda, hopefully close to a one-liner.

While we're at it, we can also expand the `verbose` decorator so that it is no longer needed. This should all reduce `import mne` time a little bit (maybe 50-100 ms?), which is nice.

**Comment by hoechenberger** [comment] 2022-02-23 13:15
> While we're at it, we can also expand the `verbose` decorator so that it is no longer needed. This should all reduce `import mne` time a little bit (maybe 50-100 ms?), which is nice.

Yes, so I was thinking of replacing `@fill_doc`, `@copy_doc`(?); and if you think we could replace the entire `@verbose` machinery as well, that'd be great.

**Comment by larsoner** [comment] 2022-02-23 14:19
> and if you think we could replace the entire @verbose machinery as well, that'd be great.

Yeah I think we might as well. At the end of the day the `@verbose` creates a new function from a string anyway. `@fill_doc` doesn't need to -- it just modifies `__doc__` -- but that should be easy enough to deal with hopefully.

**Comment by larsoner** [comment] 2023-03-25 20:40
Let's discuss further in https://github.com/mne-tools/mne-python/pull/10402 if needed, but there I closed as not-planned

**Closed by larsoner** 2023-03-25 20:40 UTC
